"use client";

import * as React from "react";
import ReactMarkdown from "react-markdown";
import {
  ArrowLeft,
  Download,
  FileText,
  FileCode2,
  Loader2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import type { PipelineResult } from "@/lib/pipeline/types";

interface Props {
  result: PipelineResult;
  onBack: () => void;
}

export function NoteView({ result, onBack }: Props) {
  const { note, meta } = result;
  const [busy, setBusy] = React.useState<"pdf" | "md" | null>(null);

  async function downloadMarkdown() {
    setBusy("md");
    try {
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "markdown", payload: { note } }),
      });
      if (!res.ok) throw new Error(await res.text());
      const blob = await res.blob();
      triggerDownload(blob, `reviewpulse-note-${slug(meta.appName)}.md`);
    } finally {
      setBusy(null);
    }
  }

  async function downloadPdf() {
    setBusy("pdf");
    try {
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "pdf", payload: { note, result } }),
      });
      if (!res.ok) throw new Error(await res.text());
      const html = await res.text();
      // open print-ready HTML in a new tab; user clicks "Save as PDF" in the
      // browser print dialog.
      const w = window.open("", "_blank");
      if (w) {
        w.document.write(html);
        w.document.close();
      } else {
        // popup blocked -- fallback to download as .html
        const blob = new Blob([html], { type: "text/html" });
        triggerDownload(blob, `reviewpulse-note-${slug(meta.appName)}.html`);
      }
    } finally {
      setBusy(null);
    }
  }

  return (
    <div className="mx-auto max-w-3xl px-6 pt-8 pb-20">
      <button
        onClick={onBack}
        className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back to dashboard
      </button>

      <div className="mt-6 rounded-2xl border border-border bg-[var(--surface)] shadow-sm overflow-hidden">
        {/* Print-style masthead */}
        <div className="flex items-center justify-between border-b-2 border-[var(--primary)] px-6 py-3 sm:px-8">
          <div className="text-lg font-bold">
            Review<span className="text-[var(--primary)]">Pulse</span>
          </div>
          <div className="text-xs text-muted-foreground">
            {note.dateRange.start} {"->"} {note.dateRange.end} | {note.wordCount} words | {meta.reviewCount} reviews
          </div>
        </div>

        <div className="px-6 py-8 sm:px-10 sm:py-10">
          <div className="text-xs text-[var(--primary)]">
            Weekly Pulse | {note.appName}
          </div>
          <h1 className="mt-2 text-3xl sm:text-4xl font-bold tracking-tight">
            {note.appName} -- Weekly Pulse
          </h1>
          <div className="mt-1 text-xs text-muted-foreground">
            Top themes | real user quotes | action ideas
          </div>

          <div className="prose-pulse mt-6 text-[15px] leading-relaxed">
            <ReactMarkdown>{note.markdown}</ReactMarkdown>
          </div>
        </div>

        <div className="border-t border-border px-6 py-3 sm:px-8 text-xs text-muted-foreground">
          Generated by ReviewPulse | Public review data only | PII-scrubbed
        </div>
      </div>

      {/* Download actions */}
      <div className="mt-6 flex flex-wrap items-center gap-3">
        <Button
          onClick={downloadPdf}
          disabled={busy !== null}
          className="rounded-full bg-[var(--primary)] text-[var(--primary-foreground)] hover:bg-[var(--primary)]/90"
        >
          {busy === "pdf" ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <FileText className="mr-2 h-4 w-4" />
          )}
          Download as PDF
        </Button>
        <Button
          onClick={downloadMarkdown}
          disabled={busy !== null}
          variant="outline"
          className="rounded-full"
        >
          {busy === "md" ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <FileCode2 className="mr-2 h-4 w-4" />
          )}
          Download as Markdown
        </Button>
        <div className="ml-auto text-xs text-muted-foreground">
          Word count: {note.wordCount} / 250 | Quotes: {note.quotes.length} | Actions: {note.actions.length}
        </div>
      </div>

      {/* CSV export */}
      <div className="mt-6 rounded-xl border border-border bg-[var(--surface)] p-4">
        <div className="flex flex-wrap items-center gap-3">
          <Download className="h-4 w-4 text-muted-foreground" />
          <div className="flex-1 min-w-0">
            <div className="font-medium text-sm">Reviews CSV used for this run</div>
            <div className="text-xs text-muted-foreground">
              {meta.reviewCount} reviews | PII-scrubbed | re-scrubbed on export
            </div>
          </div>
          <DownloadCsvButton result={result} />
        </div>
      </div>
    </div>
  );
}

function DownloadCsvButton({ result }: { result: PipelineResult }) {
  const [busy, setBusy] = React.useState(false);
  async function onClick() {
    setBusy(true);
    try {
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "csv", payload: { reviews: result.reviews } }),
      });
      if (!res.ok) throw new Error(await res.text());
      const blob = await res.blob();
      triggerDownload(blob, `reviewpulse-reviews-${slug(result.meta.appName)}.csv`);
    } finally {
      setBusy(false);
    }
  }
  return (
    <Button variant="outline" size="sm" onClick={onClick} disabled={busy} className="rounded-full">
      {busy ? <Loader2 className="mr-2 h-3 w-3 animate-spin" /> : <Download className="mr-2 h-3 w-3" />}
      Download CSV
    </Button>
  );
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 500);
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
